version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: "%(asctime)s - %(levelname)s - %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    formatter: standard
    level: INFO
    stream: ext://sys.stdout

  file:
    class: logging.handlers.WatchedFileHandler
    formatter: standard
    filename: molclass.log
    level: INFO


loggers:
  uvicorn:
    error:
      propagate: true
    access:
      propagate: true

root:
  level: DEBUG
  handlers: [console, file]
  propagate: yes