name: Package Application with Pyinstaller for Windows

on:
  release:
    types: [created]
  workflow_dispatch:


jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Create virtual environment
      run: python -m venv myenv
      shell: powershell
      
    - name: Activate virtual environment
      run: .\myenv\Scripts\Activate.ps1
      shell: powershell

    - name: Install requirements
      run: pip install -r requirements\requirements.txt

    - name: PyInstaller
      run: pyinstaller --clean --name molclass --onefile main.py

    - name: List contents of dist directory
      run: ls dist

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: dist/molclass.exe
        asset_name: Molclass.exe
        tag: ${{ github.ref }}
        overwrite: true