name: Package Application with Pyinstaller for Windows

on:
  release:
    types: [created]
  workflow_dispatch:


jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
      
    - name: Activate virtual environment
      run: .\myenv\Scripts\Activate.ps1
      shell: powershell

    - name: Install requirements
      run: pip install -r requirements.txt

    - name: PyInstaller
      run: pyinstaller --clean --name molclass --onefile main.py

    - name: List contents of dist directory
      run: ls dist

    - name: Upload Windows Artifact
      uses: actions/upload-artifact@v3
      id: upload_artifacts_windows
      with:
        name: Molclass.exe
        path: dist/molclass.exe